name: Trigger Private Repository Workflow

on:
#  release:
#    types: [created]
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow in private repository
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        APP_NAME: "kmc-ng"
        TAG: ${{ github.ref_name }}
      run: |
         echo ${{ github.event.repository.name }}
#        curl -L \
#        -X POST \
#        -H "Accept: application/vnd.github+json" \
#        -H "Authorization: Bearer $ACCESS_TOKEN" \
#        https://api.github.com/repos/kaltura/ovp-statboy/actions/workflows/deploy-uiconf.yaml/dispatches \
#        -d "{\"ref\":\"workflow-uiconf-trigger\",\"inputs\":{\"env\":\"nvq2\",\"app_name\":\"$APP_NAME\",\"tag\":\"$TAG\"}}"
